"""Write assessment results as JSON, CSV, Markdown, or a self-contained HTML report."""

from __future__ import annotations

import csv
import io
import json
from html import escape

from .checks import FAIL, NOT_APPLICABLE, NOT_ASSESSED, PASS
from .engine import AssessmentResult

DISCLAIMER = (
    "This report is generated by an automated assessment aid. It does not replace a formal "
    "assessment, authorization decision, or the judgment of a qualified auditor. Controls "
    "without automated checks are reported as not assessed and require manual review."
)

_STATUS_TEXT = {PASS: "Pass", FAIL: "Fail", NOT_ASSESSED: "Not assessed", NOT_APPLICABLE: "Not applicable"}


def _pct(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.1f}%"


def to_json(result: AssessmentResult) -> str:
    return json.dumps(result.to_dict(), indent=2, default=str)


def to_csv(result: AssessmentResult) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["rule_id", "title", "controls", "severity", "status", "detail",
                     "failing_items", "remediation"])
    for r in result.rules:
        writer.writerow([r.rule_id, r.title, "; ".join(r.controls), r.severity,
                         _STATUS_TEXT[r.status], r.detail, "; ".join(r.failing_items), r.remediation])
    return buf.getvalue()


def to_markdown(result: AssessmentResult) -> str:
    lines = [
        f"# NIST SP 800-53 assessment: {result.organization}",
        "",
        f"Baseline: **{result.baseline.title()}** | Sector: {result.sector} | Generated: {result.generated_at}",
        "",
        f"- Compliance (automated checks passed): **{_pct(result.compliance_pct)}**",
        f"- Weighted risk exposure: **{result.risk_score:.1f} / 100 ({result.risk_rating})**",
        f"- Checks: {result.rule_counts[PASS]} passed, {result.rule_counts[FAIL]} failed, "
        f"{result.rule_counts[NOT_ASSESSED]} not assessed, {result.rule_counts[NOT_APPLICABLE]} not applicable",
        "",
        "## Findings by priority",
        "",
    ]
    if not result.findings:
        lines.append("No failed checks.")
    for f in result.findings:
        lines += [
            f"### [{f.severity.upper()}] {f.rule_id}: {f.title}",
            f"Controls: {', '.join(f.controls)}  ",
            f"Observation: {f.detail}  ",
        ]
        if f.failing_items:
            lines.append(f"Affected: {', '.join(f.failing_items)}  ")
        lines += [f"Remediation: {f.remediation}", ""]
    lines += ["## Control status", "", "| Control | Title | Status |", "|---|---|---|"]
    for c in result.controls:
        lines.append(f"| {c.control_id} | {c.title} | {c.status} |")
    lines += ["", "## Compliance by control family", "", "| Family | Checks assessed | Compliance |", "|---|---|---|"]
    for fam in result.families:
        lines.append(f"| {fam.family} {fam.family_name} | {fam.rules_assessed} | {_pct(fam.compliance_pct)} |")
    lines += ["", f"_{DISCLAIMER}_", ""]
    return "\n".join(lines)


_CSS = """
:root{--ink:#1d2939;--muted:#5b6675;--line:#d5dae0;--paper:#fff;--wash:#f5f7f9;
--fail:#b42318;--pass:#1e7b4f;--partial:#a15c07;--na:#5b6675}
*{box-sizing:border-box}
body{margin:0;background:var(--wash);color:var(--ink);
font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif}
main{max-width:980px;margin:0 auto;padding:40px 24px 64px;background:var(--paper)}
h1,h2,h3{font-family:Charter,"Bitstream Charter","Iowan Old Style",Georgia,serif;line-height:1.25}
h1{font-size:30px;margin:0 0 6px}
h2{font-size:21px;margin:44px 0 12px;padding-bottom:6px;border-bottom:2px solid var(--ink)}
h3{font-size:16px;margin:0 0 6px}
.meta{color:var(--muted);margin:0}
.summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:0;margin-top:28px;
border:1px solid var(--line)}
.summary div{padding:16px 18px;border-right:1px solid var(--line)}
.summary div:last-child{border-right:0}
.figure{font-family:Charter,Georgia,serif;font-size:34px;font-weight:700;display:block}
.label{color:var(--muted);font-size:13px}
.finding{border-left:4px solid var(--fail);padding:12px 16px;margin:14px 0;background:var(--wash)}
.finding.medium{border-left-color:var(--partial)}.finding.low{border-left-color:var(--na)}
.finding p{margin:4px 0}
.sev{display:inline-block;font-size:12px;font-weight:700;padding:1px 8px;border-radius:3px;
color:#fff;background:var(--fail);margin-right:6px}
.sev.medium{background:var(--partial)}.sev.low{background:var(--na)}
.table-wrap{overflow-x:auto}
table{border-collapse:collapse;width:100%;font-size:14px}
th,td{text-align:left;padding:7px 10px;border-bottom:1px solid var(--line);vertical-align:top}
th{font-weight:600;color:var(--muted)}
.s-Implemented,.s-Pass{color:var(--pass);font-weight:600}
.s-Not-implemented,.s-Fail{color:var(--fail);font-weight:600}
.s-Partially-implemented{color:var(--partial);font-weight:600}
.s-Not-assessed,.s-Not-applicable{color:var(--na)}
.bar{background:var(--wash);height:10px;min-width:120px;border:1px solid var(--line)}
.bar span{display:block;height:100%;background:var(--ink)}
.disclaimer{margin-top:40px;color:var(--muted);font-size:13px}
@media print{body{background:#fff}main{padding:0}}
"""


def _cls(status: str) -> str:
    return "s-" + status.replace(" ", "-")


def to_html(result: AssessmentResult) -> str:
    e = escape
    findings_html = []
    for f in result.findings:
        sev = "medium" if f.severity == "medium" else ("low" if f.severity == "low" else "")
        affected = (f"<p><strong>Affected:</strong> {e(', '.join(f.failing_items))}</p>"
                    if f.failing_items else "")
        findings_html.append(
            f'<div class="finding {sev}"><h3><span class="sev {sev}">{e(f.severity.title())}</span>'
            f'{e(f.rule_id)}: {e(f.title)}</h3>'
            f'<p><strong>Controls:</strong> {e(", ".join(f.controls))}</p>'
            f'<p><strong>Observation:</strong> {e(f.detail)}</p>{affected}'
            f'<p><strong>Remediation:</strong> {e(f.remediation)}</p></div>'
        )
    if not findings_html:
        findings_html.append("<p>No failed checks.</p>")

    fam_rows = []
    for fam in result.families:
        pct = fam.compliance_pct
        bar = (f'<div class="bar" role="img" aria-label="{pct:.0f} percent"><span style="width:{pct}%"></span></div>'
               if pct is not None else "")
        fam_rows.append(f"<tr><td>{e(fam.family)}</td><td>{e(fam.family_name)}</td>"
                        f"<td>{fam.rules_assessed}</td><td>{_pct(pct)}</td><td>{bar}</td></tr>")

    ctrl_rows = "".join(
        f'<tr><td>{e(c.control_id)}</td><td>{e(c.title)}</td>'
        f'<td class="{_cls(c.status)}">{e(c.status)}</td><td>{e(", ".join(c.rules)) or "Manual review"}</td></tr>'
        for c in result.controls
    )
    rule_rows = "".join(
        f'<tr><td>{e(r.rule_id)}</td><td>{e(r.title)}</td><td>{e(r.severity.title())}</td>'
        f'<td class="{_cls(_STATUS_TEXT[r.status])}">{_STATUS_TEXT[r.status]}</td><td>{e(r.detail)}</td></tr>'
        for r in result.rules
    )
    rc = result.rule_counts
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>NIST SP 800-53 assessment: {e(result.organization)}</title>
<style>{_CSS}</style></head>
<body><main>
<h1>NIST SP 800-53 assessment: {e(result.organization)}</h1>
<p class="meta">{e(result.baseline.title())} baseline. Sector: {e(result.sector)}. Generated {e(result.generated_at)} by grc_assess {e(result.tool_version)}.</p>
<section class="summary" aria-label="Summary">
<div><span class="figure">{result.risk_score:.0f}<small style="font-size:16px"> / 100</small></span><span class="label">Weighted risk exposure ({e(result.risk_rating)})</span></div>
<div><span class="figure">{_pct(result.compliance_pct)}</span><span class="label">Automated checks passed</span></div>
<div><span class="figure">{rc[FAIL]}</span><span class="label">Failed checks</span></div>
<div><span class="figure">{rc[NOT_ASSESSED]}</span><span class="label">Checks lacking data</span></div>
</section>
<h2>Findings by priority</h2>
{''.join(findings_html)}
<h2>Compliance by control family</h2>
<div class="table-wrap"><table><thead><tr><th>Family</th><th>Name</th><th>Checks</th><th>Compliance</th><th></th></tr></thead>
<tbody>{''.join(fam_rows)}</tbody></table></div>
<h2>Control status</h2>
<div class="table-wrap"><table><thead><tr><th>Control</th><th>Title</th><th>Status</th><th>Evidence checks</th></tr></thead>
<tbody>{ctrl_rows}</tbody></table></div>
<h2>All checks</h2>
<div class="table-wrap"><table><thead><tr><th>Check</th><th>Title</th><th>Severity</th><th>Result</th><th>Detail</th></tr></thead>
<tbody>{rule_rows}</tbody></table></div>
<p class="disclaimer">{e(DISCLAIMER)}</p>
</main></body></html>
"""


WRITERS = {"json": to_json, "csv": to_csv, "md": to_markdown, "html": to_html}
